#!/usr/bin/env node

/**
 * Setup Wizard for Compliance Command Center
 * Interactive configuration and deployment assistant
 */

const readline = require("readline");
const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

const config = {
  catalyst: {},
  zia: {},
  creator: {},
  cliq: {},
  email: {},
};

console.log(`
╔═══════════════════════════════════════════════════════════════╗
║                                                               ║
║     🛡️  COMPLIANCE COMMAND CENTER - SETUP WIZARD 🛡️         ║
║                                                               ║
║     Zoho Cliqtrix 2025 Contest Entry                        ║
║     Interactive Configuration & Deployment                    ║
║                                                               ║
╚═══════════════════════════════════════════════════════════════╝
`);

async function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

async function setupWizard() {
  console.log("\n📋 STEP 1: Zoho Catalyst Configuration\n");

  config.catalyst.projectId = await question(
    "Enter your Catalyst Project ID: "
  );
  config.catalyst.region =
    (await question("Enter Catalyst Region (US/EU/IN) [US]: ")) || "US";
  config.catalyst.baseUrl = `https://${config.catalyst.projectId}.catalyst.zoho.${config.catalyst.region.toLowerCase() === "us" ? "com" : config.catalyst.region.toLowerCase()}`;

  console.log("\n🧠 STEP 2: Zia Skills Configuration\n");

  const hasZiaAccess =
    (await question("Do you have Zia Skills API access? (yes/no) [yes]: ")) ||
    "yes";
  if (hasZiaAccess.toLowerCase() === "yes") {
    config.zia.apiUrl = "https://zia.zoho.com/api/v1";
    config.zia.modelId =
      (await question(
        "Enter Zia Compliance Extractor Model ID (or press Enter to create later): "
      )) || "compliance_extractor_v1";
  } else {
    console.log(
      "⚠️  Zia Skills will use rule-based extraction until models are configured."
    );
    config.zia.apiUrl = "disabled";
  }

  console.log("\n📊 STEP 3: Zoho Creator Configuration\n");

  config.creator.appId =
    (await question("Enter Creator App Name [compliance_tracker]: ")) ||
    "compliance_tracker";
  config.creator.owner = await question("Enter Creator Owner Email: ");

  console.log("\n💬 STEP 4: Zoho Cliq Configuration\n");

  config.cliq.orgId = await question("Enter Cliq Organization ID: ");
  config.cliq.complianceChannelId =
    (await question("Enter Compliance Team Channel ID (optional): ")) ||
    "compliance-team";

  console.log("\n📧 STEP 5: Email Configuration\n");

  config.email.complianceTeam = await question("Enter Compliance Team Email: ");
  config.email.noReply =
    (await question("Enter No-Reply Email [no-reply@company.com]: ")) ||
    "no-reply@company.com";

  console.log("\n⚙️  STEP 6: Advanced Configuration\n");

  config.riskThreshold = parseFloat(
    (await question("Enter Risk Alert Threshold (0-10) [7.5]: ")) || "7.5"
  );
  config.autoReportSchedule =
    (await question(
      "Auto Report Frequency (daily/weekly/monthly) [weekly]: "
    )) || "weekly";

  // Generate .env file
  generateEnvFile(config);

  console.log("\n✅ Configuration saved to .env\n");

  // Ask about deployment
  const deployNow =
    (await question("Do you want to deploy now? (yes/no) [no]: ")) || "no";

  if (deployNow.toLowerCase() === "yes") {
    await deployApplication();
  } else {
    console.log("\n📝 To deploy later, run: npm run deploy:all\n");
  }

  // Generate setup summary
  generateSetupSummary(config);

  console.log("\n✨ Setup complete! Check setup-summary.md for next steps.\n");

  rl.close();
}

function generateEnvFile(config) {
  const envContent = `# Compliance Command Center Configuration
# Generated by Setup Wizard on ${new Date().toISOString()}

# Catalyst Configuration
CATALYST_PROJECT_ID=${config.catalyst.projectId}
CATALYST_REGION=${config.catalyst.region}
CATALYST_BASE_URL=${config.catalyst.baseUrl}

# Zia Configuration
ZIA_API_URL=${config.zia.apiUrl}
ZIA_MODEL_ID=${config.zia.modelId || "compliance_extractor_v1"}
ZIA_INTENT_MODEL_ID=compliance_intent_v1

# Creator Configuration
CREATOR_APP_ID=${config.creator.appId}
CREATOR_OWNER=${config.creator.owner}

# Cliq Configuration
CLIQ_ORG_ID=${config.cliq.orgId}
COMPLIANCE_TEAM_CHANNEL_ID=${config.cliq.complianceChannelId}

# Email Configuration
COMPLIANCE_TEAM_EMAIL=${config.email.complianceTeam}
NO_REPLY_EMAIL=${config.email.noReply}

# Risk & Alert Settings
RISK_THRESHOLD=${config.riskThreshold}
ALERT_DAYS_AHEAD=3
AUTO_REPORT_SCHEDULE=${config.autoReportSchedule}

# External Storage (Configure if needed)
# AWS_S3_BUCKET=compliance-audit-logs
# AWS_ACCESS_KEY_ID=your_key
# AWS_SECRET_ACCESS_KEY=your_secret

# Optional Integrations
# ZOHO_PROJECTS_PORTAL=your_portal
# ZOHO_WRITER_TEMPLATE_ID=your_template_id
`;

  fs.writeFileSync(".env", envContent);
  console.log("✅ .env file created");
}

async function deployApplication() {
  console.log("\n🚀 Starting deployment...\n");

  try {
    // Check if Catalyst CLI is installed
    console.log("1️⃣  Checking Catalyst CLI...");
    execSync("catalyst --version", { stdio: "inherit" });

    // Deploy Catalyst backend
    console.log("\n2️⃣  Deploying Catalyst backend...");
    execSync(
      "cd catalyst && catalyst datastore deploy && catalyst functions deploy && catalyst cron deploy",
      { stdio: "inherit" }
    );

    // Check if Cliq extension toolkit is installed
    console.log("\n3️⃣  Checking Cliq Extension Toolkit...");
    try {
      execSync("zoho-extension-toolkit --version", { stdio: "inherit" });

      // Deploy Cliq bot
      console.log("\n4️⃣  Deploying Cliq bot...");
      execSync("cd cliq-bot && zoho-extension-toolkit deploy", {
        stdio: "inherit",
      });
    } catch (error) {
      console.log(
        "⚠️  Cliq Extension Toolkit not found. Please install manually and run: npm run deploy:bot"
      );
    }

    // Deploy widget
    console.log("\n5️⃣  Deploying dashboard widget...");
    execSync("cd widget && catalyst hosting deploy", { stdio: "inherit" });

    console.log("\n✅ Deployment complete!\n");
  } catch (error) {
    console.error("\n❌ Deployment failed:", error.message);
    console.log("\n📝 Please deploy manually using: npm run deploy:all\n");
  }
}

function generateSetupSummary(config) {
  const summary = `# Setup Summary

**Configuration Date:** ${new Date().toLocaleString()}

## Configured Services

### Catalyst
- Project ID: ${config.catalyst.projectId}
- Region: ${config.catalyst.region}
- Base URL: ${config.catalyst.baseUrl}

### Zia Skills
- API URL: ${config.zia.apiUrl}
- Model ID: ${config.zia.modelId || "Not configured"}

### Creator
- App ID: ${config.creator.appId}
- Owner: ${config.creator.owner}

### Cliq
- Organization ID: ${config.cliq.orgId}
- Compliance Channel: ${config.cliq.complianceChannelId}

### Email
- Compliance Team: ${config.email.complianceTeam}
- No-Reply: ${config.email.noReply}

## Next Steps

1. ✅ Configuration saved to .env
2. 📦 Install dependencies: \`npm install\`
3. 🚀 Deploy application: \`npm run deploy:all\`
4. 🧪 Run tests: \`npm test\`
5. 📚 Read setup guide: \`docs/setup-guide.md\`

## Manual Configuration Required

### Zoho Creator
1. Create app: ${config.creator.appId}
2. Import forms from \`creator-forms/\` directory
3. Configure OAuth connections

### Zia Skills
1. Upload model configs from \`zia-skills/\` directory
2. Prepare training data
3. Train models: \`zia-cli train-model --model-id ${config.zia.modelId}\`

### Zoho Cliq
1. Install bot from \`cliq-bot/\` directory
2. Configure webhooks
3. Enable in channels: \`/compliance-monitor on\`

## Verification

Test the installation:
\`\`\`bash
# Test bot
/compliance-help

# Test health score
/compliance-health

# Test risk prediction
/compliance-risks 7
\`\`\`

## Support

- Documentation: docs/setup-guide.md
- Troubleshooting: docs/troubleshooting.md
- Repository: https://github.com/yourusername/compliance-command-center

---
Generated by Compliance Command Center Setup Wizard
`;

  fs.writeFileSync("setup-summary.md", summary);
  console.log("✅ setup-summary.md created");
}

// Run wizard
setupWizard().catch((error) => {
  console.error("Setup wizard error:", error);
  rl.close();
  process.exit(1);
});
